#
# Copyright (c) 2020 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#

obj-$(CONFIG_EXYNOS_LPD) += lpd_drv.o
lpd_drv-$(CONFIG_EXYNOS_LPD) += lpd.o lpd_dbg.o lpd_dev.o lpd_noti.o lpd_mem.o lpd_config_noti.o
